// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYW5vj6mzfCmsNasVbke9ds6CQEoRI8-Q',
    appId: '1:119042707336:web:fbc6e3680c2fb9f299343d',
    messagingSenderId: '119042707336',
    projectId: 'libs-e-commerce-app',
    authDomain: 'libs-e-commerce-app.firebaseapp.com',
    storageBucket: 'libs-e-commerce-app.firebasestorage.app',
    measurementId: 'G-GWTJLPT6H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB65v6Im5kxzi-MYb919rMxwxTeLJcvU2I',
    appId: '1:119042707336:android:13f9597ac93924b799343d',
    messagingSenderId: '119042707336',
    projectId: 'libs-e-commerce-app',
    storageBucket: 'libs-e-commerce-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo5CXZ5KkmQ-X8-nCxKy5b7wWIHWEIcYs',
    appId: '1:119042707336:ios:aae20cfc9aa252ca99343d',
    messagingSenderId: '119042707336',
    projectId: 'libs-e-commerce-app',
    storageBucket: 'libs-e-commerce-app.firebasestorage.app',
    iosBundleId: 'com.example.libsECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo5CXZ5KkmQ-X8-nCxKy5b7wWIHWEIcYs',
    appId: '1:119042707336:ios:aae20cfc9aa252ca99343d',
    messagingSenderId: '119042707336',
    projectId: 'libs-e-commerce-app',
    storageBucket: 'libs-e-commerce-app.firebasestorage.app',
    iosBundleId: 'com.example.libsECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYW5vj6mzfCmsNasVbke9ds6CQEoRI8-Q',
    appId: '1:119042707336:web:50e9702405956ceb99343d',
    messagingSenderId: '119042707336',
    projectId: 'libs-e-commerce-app',
    authDomain: 'libs-e-commerce-app.firebaseapp.com',
    storageBucket: 'libs-e-commerce-app.firebasestorage.app',
    measurementId: 'G-LRPPSN9SKF',
  );
}
